services:
  web:
    image: 0xfc2f/fastapi-book-project:latest
    container_name: web
    ports:
      - "5000:5000"
    networks:
      - app_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "100k"
  nginx:
    build: 
      context: ./nginx  # Assuming you'll put the Dockerfile in a nginx directory
      dockerfile: ./nginx/Dockerfile
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - app_network  # Make sure nginx is explicitly in the network
networks:
  app_network:
    driver: bridge