services:
  web:
    image: 0xfc2f/fastapi-book-project:latest
    container_name: web
    ports:
      - "5000:5000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "100k"
    networks:
      - mynetwork

  proxy:
    image: nginx:latest  # Specify the latest tag for nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - mynetwork
    restart: unless-stopped # Add restart policy to nginx

networks:
  mynetwork: