name: Deploy to Render


# .github/workflows/ci.yml

on:
  pull_request:
    types:
      - closed
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest
      - name: Deploy to render
        # Only run this step if the branch is main
        # if: github.ref == 'refs/heads/main'
        if: github.event.pull_request.merged == true
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"