name: Deploy to Render


on:
  pull_request:
    types:
      - closed
    branches: [main]
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Render
    needs: test
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # Only run this step if the branch is main
      # if: github.ref == 'refs/heads/main'
      - name:
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            curl "$deploy_url"